name: py3
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py310h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - aiohttp==3.8.3
    - aiohttp-jinja2==1.5
    - aiosignal==1.3.1
    - anyio==3.6.2
    - async-timeout==4.0.2
    - attr==0.3.2
    - attrs==22.2.0
    - autoflake==2.0.1
    - black==23.1.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - clickclick==20.10.2
    - connexion==2.14.2
    - flask==2.2.2
    - frozenlist==1.3.3
    - h11==0.14.0
    - httpcore==0.16.3
    - httpx==0.23.3
    - idna==3.4
    - inflection==0.5.1
    - isort==5.12.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jsonschema==4.17.3
    - markupsafe==2.1.2
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - openapi-python-client==0.13.1
    - packaging==23.0
    - pathspec==0.11.0
    - platformdirs==3.0.0
    - pydantic==1.10.4
    - pyflakes==3.0.1
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - requests==2.28.2
    - rfc3986==1.5.0
    - shellingham==1.5.0.post1
    - six==1.16.0
    - sniffio==1.3.0
    - swagger-ui-bundle==0.0.9
    - tomli==2.0.1
    - typer==0.7.0
    - typing-extensions==4.4.0
    - urllib3==1.26.14
    - websocket-client==1.4.2
    - websockets==10.4
    - werkzeug==2.2.2
    - yarl==1.8.2